"use client";

import { BottomNav } from "@/components/bottom-nav";
import { useTheme } from "@/components/theme-provider";

export default function SettingsPage() {
  const { theme, setTheme } = useTheme();
  return <main className="mx-auto flex min-h-screen w-full max-w-xl flex-col bg-stone-50 px-5 pb-28 pt-8 text-stone-950 dark:bg-stone-950 dark:text-stone-50 sm:px-8"><p className="text-sm font-semibold uppercase tracking-[0.18em] text-emerald-700">Settings</p><h1 className="mt-3 text-3xl font-bold tracking-tight">App settings</h1><p className="mt-4 leading-7 text-stone-600 dark:text-stone-300">Choose how VunaLink looks on your device.</p><section className="mt-8 rounded-2xl border border-stone-200 bg-white p-4 shadow-sm dark:border-stone-700 dark:bg-stone-900" aria-labelledby="appearance-title"><h2 id="appearance-title" className="font-semibold">Appearance</h2><div className="mt-4 grid grid-cols-2 gap-3" role="group" aria-label="Choose appearance"><button type="button" aria-pressed={theme === "light"} onClick={() => setTheme("light")} className={`min-h-14 rounded-xl border px-4 text-left font-medium focus-visible:outline-2 focus-visible:outline-emerald-700 ${theme === "light" ? "border-emerald-700 bg-emerald-50 text-emerald-900" : "border-stone-200 text-stone-600 dark:border-stone-700 dark:text-stone-300"}`}>Light<span className="mt-1 block text-xs font-normal opacity-75">Bright and clear</span></button><button type="button" aria-pressed={theme === "dark"} onClick={() => setTheme("dark")} className={`min-h-14 rounded-xl border px-4 text-left font-medium focus-visible:outline-2 focus-visible:outline-emerald-700 ${theme === "dark" ? "border-emerald-500 bg-emerald-950 text-emerald-100" : "border-stone-200 text-stone-600 dark:border-stone-700 dark:text-stone-300"}`}>Dark<span className="mt-1 block text-xs font-normal opacity-75">Easier on the eyes</span></button></div></section><BottomNav /></main>;
}
